---
- name: Configure Builders
  hosts: builders
  remote_user: ec2-user
  become: yes

  roles:
    - common
    - docker

  tasks:
    - name: Run presidio anonymiser
      community.docker.docker_container:
        name: presidio-anonymiser
        image: mcr.microsoft.com/presidio-anonymizer
        ports: "5001:3000"       