---
- name: Configure Builders
  hosts: webservers
  remote_user: ec2-user
  become: yes

  pre_tasks:
    - name: Set TimeZone
      timezone:
        name: Europe/Dublin
      become: True
  roles:
    - common
    - docker
    - website